name: AGR-PR-pipeline
	
	on:
	  workflow_call:
	    inputs:
	      runner-tag:
	        description: Runner tag to run workflow on.
	        type: string
	        default: scanner
	
	# Stop in-progress runs from previous commits so we don't waste resources.
	concurrency:
	  group: ${{github.workflow}}-${{github.ref}}
	  cancel-in-progress: true
	
	jobs:
	  build:
	    name: Build
	    runs-on: ${{inputs.runner-tag}}
	
	    steps:
	      - id: input_check
	        name: Check Workflow Inputs
	        run: |
	          echo "Stubs. Input checks complete"
	
	      - id: static_checks
	        name: Run static checks
	        run: |
	          echo "Stubs. Static checks complete"
	
	      - id: build
	        name: Run build
	        run: |
	          echo "Stubs. Build complete"
	
	      - id: dynamic_checks
	        name: Run dynamic checks
	        run: |
	          echo "Stubs. Dynamic checks complete"
	
	  summary:
	    name: AGR PR Pipeline Summary
	    needs: build
	    runs-on: k8s
	
	    steps:
	      - id: display_summary
	        name: Display summary
	        if: always()
	        run: |
	            echo '## Summary' >> $GITHUB_STEP_SUMMARY
	            echo "|Job|Result|" >> $GITHUB_STEP_SUMMARY
	            echo "|-|-|" >> $GITHUB_STEP_SUMMARY
	            echo "|build|\`${{needs.build.result}}\`|" >> $GITHUB_STEP_SUMMARY
