name: Code Checks
on:
  push:
  pull_request:

jobs:
  check-code:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      id: checkout
      uses: actions/checkout@v2
      
    - name: Set up Python and install dependencies
      id: python-checks
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
        run: |
         python -m pip install --upgrade pip
         pip install flake8 mypy
        
         # Python code linting
         flake8 --exclude=venv*,.venv*
        
         # Python type checking
         mypy --strict ./
        
    - name: Set up C and C++ and compile code
      id: c-cpp-checks
      run: |
        sudo apt-get install build-essential
        
        # Compile and check C/C++ code
        find . \( -name "*.c" -o -name "*.cpp" \) -type f -print0 | while IFS= read -r -d '' file; do
          extension="${file##*.}"
          filename="${file%.*}"
          
          if [[ "$extension" == "c" ]]; then
            gcc -o "$filename" "$file"
          elif [[ "$extension" == "cpp" ]]; then
            g++ -o "$filename" "$file"
          fi
          
          "./$filename"
        done
