name: Code Checks
on:
  push:
  pull_request:

jobs:
  check-code:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@v2
      
    - name: Set up Python and install dependencies
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
        
    - name: Set up C and C++ static analysis tools
      run: sudo apt-get install cppcheck
      
    - name: Run code checks
      run: |
        python -m pip install --upgrade pip
        pip install flake8 mypy
        
        find . \( -name "*.py" -o -name "*.c" -o -name "*.cpp" \) -type f -print0 | while IFS= read -r -d '' file; do
          extension="${file##*.}"
          filename="${file%.*}"
          
          if [[ "$extension" == "py" ]]; then
            flake8 --exclude=venv*,.venv* "$file"
            mypy --strict "$file"
          elif [[ "$extension" == "c" || "$extension" == "cpp" ]]; then
            cppcheck --enable=all --std=c++11 "$file"
          fi
        done
