name: Python application

on:
  repository_dispatch:
   types: [my-event]
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        echo "${{ secrets.DOCKERPW }}" | docker login -u "ps3291" --password-stdin
        docker image build -t ps3291/pyflask:latest .
        docker push ps3291/pyflask:latest
